config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  get 'about' => 'pages#about'
  get 'lessons' => 'pages#lessons'
  get 'belts' => 'pages#belts'
  get 'planes' => 'pages#planes'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
  end

  def about
  end

  def lessons
    @lessons = [
      { title: 'Getting Started',
        sites: [
          { name: 'Lightbot', url: 'http://lightbot.com/flash.html', image: 'lightbot.png' },
          { name: 'Scratch', url: 'http://scratch.mit.edu/', image: 'scratch.png' },
          { name: 'Code Combat', url: 'http://codecombat.com/', image: 'codecombat.png' },
          { name: 'Code.org', url: 'https://code.org/student/elementary', image: 'codeorg.png' },
        ]
      },
      { title: 'Learn How to Make Websites',
        sites: [
          { name: 'Dash', url: 'https://dash.generalassemb.ly/projects/annas-website-1', image: 'dash.png' },
          { name: 'Code Academy', url: 'http://www.codecademy.com/en/skills/make-a-website/resume', image: 'codeacademy.png' },
          { name: 'Khan Academy', url: 'https://www.khanacademy.org/computing/computer-programming/html-css', image: 'khanacademy.png' }
        ]
      },
      { title: 'Learn a Programing Language',
        sites: [
          { name: 'Try Ruby', url: 'http://tryruby.org/', image: 'tryruby.png' },
          { name: 'Code Academy: Ruby', url: 'http://www.codecademy.com/en/tracks/ruby', image: 'codeacademy_ruby.png' },
          { name: 'Code Academy: Javascript', url: 'http://www.codecademy.com/en/tracks/javascript', image: 'codeacademy_javascript.png' },
          { name: 'Khan Academy: Javascript', url: 'https://www.khanacademy.org/computing/computer-programming/programming', image: 'khanacademy_javascript.png' }
        ]
      }
    ]
  end

  def belts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lancaster CoderDojo</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

  <header>
  <%= nav_bar :fixed => :top, :brand => "Lancaster CoderDojo", :responsive => true do %>
    <%= menu_group do %>
      <%= menu_item "Home", root_path %>
      <%= menu_item "About", about_path %>
      <%= menu_item "Lessons", lessons_path %>
    <% end %>
  <% end %>

  </header>
  <div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </div>
  <hr>
  <footer>
    <div class="container">
      <div class="row">
      </div>
    </div>
  </footer>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-45843639-7', 'auto');
    ga('send', 'pageview');
  </script>
</body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h1>About Us</h1>
      <p class="lead"><a href="https://coderdojo.com/">CoderDojo</a> is a global network of free, volunteer-led, independent, community based programming clubs for young people. These young people, between 7 and 17, learn how to code, develop websites, apps, programs, games and explore technology in an informal and creative environment. In addition to learning to code, attendees meet like-minded people and get to show off what they’ve been working on.</p>

      <p class="lead">There is a focus on community, peer learning, youth mentoring and self-led learning with an emphasis on openness, helping others and showing how coding is a force for change in the world. CoderDojo makes development and learning to code a fun, sociable experience.</p>

      <p class="lead">If you have any questions about the Lancaster, PA CoderDojo, please email us at <a href="mailto:lancaster.pa.us@coderdojo.com">lancaster.pa.us@coderdojo.com</a>
    </div>
  </div>
</div>

app/views/pages/belts.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h1>Belts</h1>

      <p class="lead">Complete the projects below and earn a ninja programming belt!</p>

      <table class="table table-striped lead table-bordered">
        <tr>
          <td></td>
          <td>Finish the 1st level of Lightbot and create your first Scratch project</td>
        </tr>
        <tr>
          <td></td>
          <td>Finish the 2nd level of Lightbot and create a Scratch project involving loops and if/then statements</td>
        </tr>
        <tr>
          <td>White</td>
          <td>Finish the 3rd level of Lightbot and create a Scratch project involving variables and functions</td>
        </tr>
        <tr>
          <td></td>
          <td>Create a simple webpage with HTML and CSS</td>
        </tr>
        <tr>
          <td>Red</td>
          <td>Create a website with multiple pages, including links and images</td>
        </tr>
        <tr>
          <td></td>
          <td>Learn a programming language like PHP or Javascript</td>
        </tr>
        <tr>
          <td>Black</td>
          <td>Use a programming language to create a dynamic website that takes a user's input and processes it in some way</td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<div class="container">
  <div class="jumbotron text-center">
    <div class="row">
      <div class="col-lg-6">
        <h1>Lancaster<br/>CoderDojo</h1>
        <h3>A free computer club for kids in the Lancaster, PA area</h3>
      </div>
      <div class="col-lg-6"><%= image_tag 'kids.jpg' %></div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h3>We have three local CoderDojo groups &mdash; you're welcome to come to both!</h3>
      <ul class="lead">
        <li>Our <strong><a href="http://www.mtpl.info/">Manheim Township Public Library</a></strong> group meets on the second Tuesday of each month (except in July and December -- we take a break those months) from 6:30pm to 8pm.  To sign up, find the next upcoming meeting on the <a href="https://mtpl.info/events/">library calendar</a>, click on it, and follow the instructions shown.  Registration opens a few weeks before each event, so if you aren't able to sign up, try again a bit later.
        <li>Our <strong><a href="http://www.lancaster.lib.pa.us">Lancaster Public Library</a></strong> group meets on the fourth Thursday of each month from 6:30pm to 7:30pm.  <a href="http://www.eventbrite.com/e/coderdojo-free-tickets-14706442365">Click here</a> to sign up!</li>
        <li>Our <strong><a href="https://quarryvillelibrary.org/">Quarryville Public Library</a></strong> group meets on the second Thursday of each month from 6:00pm to 7:00pm.  <a href="https://quarryvillelibrary.org/event/quarryville-coder-dojo">Click here</a> to sign up!</li>
      </ul>
    </div>
  </div>
</div>

app/views/pages/lessons.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h1>Lessons</h1>

      <ul class="lead">
        <li>Find a site below that looks fun, and try it out.  If you don't like it, try another one!
        <li>If you need help, just ask someone.  If someone asks <i>you</i> for help, try to help them!
        <li>If you need to sign up for a site with a username and password, let an adult know.
        <li>And above all &mdash; have fun!
      </ul>
      <% @lessons.each do |lesson| %>
        <h2><%= lesson[:title] %></h2>
        <ul class="lessons list-inline">
        <% lesson[:sites].each do |site| %>
          <li class="text-center lead"><a href="<%= site[:url] %>"><%= image_tag site[:image], width: 220 %><br/><%= site[:name] %></a></li>
        <% end %>
        </ul>
      <% end %>

      <a href="http://scratch.mit.edu/projects/53802142/">Scratchmaster Ken's First Scratch Example</a>
    </div>
  </div>
</div>

app/views/pages/planes.html.erb
<style>
.plane-div {
  float: left;
  padding: 50px;
}
</style>

<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h1>Paper Airplanes</h1>

      <div class="plane-div">
        <a href="https://www.youtube.com/watch?v=GdZiesdZXbA"><%= image_tag 'plane1.png', { width: 300, border: 0 } %></a>
      </div>
      <div class="plane-div">
        <a href="https://www.youtube.com/watch?v=d2agrDvmtW8"><%= image_tag 'plane2.png', { width: 300, border: 0 } %></a>
      </div>
      <div class="plane-div">
        <a href="https://www.youtube.com/watch?v=a265vozzR9I"><%= image_tag 'plane3.png', { width: 300, border: 0 } %></a>
      </div>
      <div class="plane-div">
        <a href="https://www.youtube.com/watch?v=hWhVjL7Lmco"><%= image_tag 'plane4.png', { width: 300, border: 0 } %></a>
      </div>
    </div>
  </div>
</div>